# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.3
language: swift
script:
- set -o pipefail && xcodebuild test -workspace Example/RPHTTPServiceClient.xcworkspace -scheme "RPHTTPServiceClient-Example" -configuration "Debug" -destination "platform=iOS Simulator,name=iPhone 8,OS=11.3" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
